name: build-test-decision-tree

on: push


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: setup CMake
      run: mkdir build &&  /usr/local/bin/cmake . -B ./build/
    - name: run tests
      run: ./build/test/DecisionTests