name: build-test-decision-tree

on: push


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup CMake
      run: mkdir build && /usr/local/bin/cmake --build ./build